	<?php 
		$enable = $block->getConfig('enabled');
		if($enable < 1) return ; 
		$items = $block->getConfig('items');
		$speed = $block->getConfig('speed');
		$qty = $block->getConfig('qty');
		$showCart = $block->getConfig('addtocart');
		$showWishlist = $block->getConfig('wishlist');
		$showCompare = $block->getConfig('compare');
		$show_navigation = $block->getConfig('navigation');
		$show_pagination = $block->getConfig('pagination');
		$auto = $block->getConfig('auto');
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$rows = 1;
	?>
<div class="producttab-container">
<div class="title-tab">
	<ul class="tabs">
		<?php 
			$tab_contents = $block->getTabContent() ; 
	    $count=0;			
		foreach($tab_contents as $tab) {
			?>
		<li rel="tab_<?php echo $tab['id'];?>"  <?php if ($count==0) ?> class="active" > <?php echo $tab['name'];?></li>
			<?php
			$count ++; 
		}
		?>
	</ul>
</div>	
	<div class="tab_container"> 
	   <?php 
		foreach($tab_contents as $tab) {
		?>
		<div class="owl-container">
			<div id="tab_<?php echo $tab['id'];?>" class="tab_content"> 
				<div class="productTabContent owl-carousel">
					<?php 
						$i=0;
						$productItems =  $tab['productInfo']; 
						foreach($productItems as $_item) { 
								$productImage = $block->getImage($_item, $image);
						?>
							<?php if($i++%$rows==0) { ?> <div class="products-grid"> <?php } ?>
							
							<div class="item-inner">
								<div class="product-item-info">
									<div class=" product-item-images">						
										<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
										<?php echo $productImage->toHtml() ?>
										</a>
									</div>	
									<div class="product-item-details">

										<strong class="product name product-item-name">
											<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
											   href="<?php echo $block->getProductUrl($_item) ?>"
											   class="product-item-link">
												<?php echo $block->escapeHtml($_item->getName()) ?>
											</a>
										</strong>
										
										<?php echo $block->getProductPrice($_item); ?>
										<div class="box-hover">
											<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
											<div class="product-item-description">
												<p>
												<?php 
													$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
													$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
													$shortdes = $product->getShortDescription();
													if(strlen($shortdes) > 100){
													 $shortdes = substr($shortdes, 0, 100);
													 echo strip_tags($shortdes).'...';
													}else{
													 echo strip_tags($shortdes);
													}
											   ?>
											   </p>
										   </div>
											<div class="product-item-actions">
												<div class="add-to-links-secondary">

													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
														<a href="#"
														   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
														   class="action wishlist" data-action="add-to-wishlist"
														   title="<?php echo __('Wishlist') ?>">
															<span><?php echo __('Wishlist') ?></span>
														</a>
													<?php endif; ?>
													
													<div class="add-to-cart-primary">
														<?php if ($showCart): ?>

															<?php if ($_item->isSaleable()): ?>
																<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																	<button class="action tocart primary"
																			data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
																			type="button" title="<?php echo __('Add to Cart') ?>">
																		<span><?php echo __('Add to Cart') ?></span>
																	</button>
																<?php else: ?>
																	<?php
																		$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																		$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																	?>
																	<button class="action tocart primary"
																			data-post='<?php echo $postData; ?>'
																			type="button" title="<?php echo __('Add to Cart') ?>">
																		<span><?php echo __('Add to Cart') ?></span>
																	</button>
																<?php endif; ?>
															<?php else: ?>
																<?php if ($_item->getIsSalable()): ?>
																	<div class="stock available"><span><?php echo __('In stock') ?></span></div>
																<?php else: ?>
																	<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
																<?php endif; ?>
															<?php endif; ?>

														<?php endif; ?>
													</div>
													
													<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
														<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
														<a href="#" class="action compare"
														   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
														   title="<?php echo __('Compare') ?>">
															<span><?php echo __('Compare') ?></span>
														</a>
													<?php endif; ?>
												</div>	
											</div>
										</div>
										
									</div>	
								</div>	
							</div>
							
							 <?php if($i%$rows==0 || $i == count($productItems)) { ?> </div> <?php }?>
						<?php 
						}
						?>
				</div>
			</div>
		</div> 
		<?php 
		} 
		?>
	</div>
</div>
	
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){

	$(".producttab-container .tab_content").hide();
	$(".producttab-container .tab_content:first").show(); 
	$(".producttab-container ul.tabs li").removeClass("active");
	$(".producttab-container ul.tabs li:first-child").addClass("active");
	$(".producttab-container ul.tabs li").click(function() {
		$(".producttab-container ul.tabs li").removeClass("active");
		$(this).addClass("active");
		$(".producttab-container .tab_content").hide();
		$(".producttab-container .tab_content").removeClass("animate1");
		var activeTab = $(this).attr("rel"); 
		$("#"+activeTab) .addClass("animate1");
		$("#"+activeTab).fadeIn(); 
	});
	
	  $(".productTabContent").owlCarousel({
	    		items : <?php if($items) { echo $items; } else { echo 5; }?>,
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,				
				stopOnHover : true,
				navigation :true,
				pagination :false,
				items :5,
				itemsDesktop : [1400,4],
				itemsDesktopSmall : [992,3],
				itemsTablet: [767,2],
				itemsMobile : [479,1]
	});
	

});

</script> 

