
<div class="main-container">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_book_banner_images1')->toHtml(); ?>
	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Producttab\Block\Producttab')->setTemplate('Plazathemes_Producttab::producttab.phtml')->toHtml();?>
	</div>
	<div class="banner-text1">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_book_banner_text1')->toHtml(); ?>
	</div>

	<div class="colum-left">
		<div class="container-inner">
			<div class="row">
				<div class="col-md-3">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('Plazathemes_Newproductslider::newproductslider.phtml')->toHtml();?>
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_book_banner_images2')->toHtml(); ?>
					<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
				</div>
				<div class="col-md-9">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('Plazathemes_Featureproductslider::featureproductslider.phtml')->toHtml();?>
					
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_book_content_home1')->toHtml(); ?>
					
				</div>
			</div>
		</div>
	</div>
	
	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
	</div>
</div>


