
<div class="main-container">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<div class="container-inner">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_game_content_home')->toHtml(); ?>
	</div>
	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_game_banner_images1')->toHtml(); ?>
	<div class="proup-products">
		<div class="container-inner">		
			<div class="row">
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('Plazathemes_Newproductslider::newproductslider.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('Plazathemes_Bestsellerproduct::bestsellerproduct.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Mostviewed\Block\Products')->setTemplate('Plazathemes_Mostviewed::productslider.phtml')->toHtml();?>
				</div>
				
			</div>
		</div>
	</div>
	<div class="container-inner">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_game_banner_images2')->toHtml(); ?>
		<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
	</div>

</div>


