<?php $block->renderFileLessToCss(); ?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_top')->toHtml();?>
<header class="header-container">
		<div class="top-bar visible-lg visible-md">
			<div class="container-inner">
				<div class="container-size">
					<div class="row">
						<div class="col-sm-5">
							<?php echo $this->getChildHtml("store_language"); ?>
							<?php echo $this->getChildHtml("currency"); ?>	
						</div>
						<div class="col-sm-7">
							<?php echo $this->getChildHtml("header.links"); ?>
						</div>		
					</div>
				</div>
			</div>
		</div>
		<div class="header-content">
			<div class="container-inner">
				<div class="row">
					<div class="col-md-3">						
						<div class="logo-home"><?php echo $this->getChildHtml("logo"); ?></div>					
					</div>					
					<div class="col-md-9">
						<div class="header-support">
							<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_support')->toHtml();?>
						</div>
						
						<?php echo $this->getChildHtml("minicart");?>
						<?php echo $this->getChildHtml("top.search"); ?>
						
					</div>
				</div>
			</div>
		</div>
		<div class="nav-ozmegamenu">
			<div class="container-inner visible-lg visible-md">
					<?php echo $this->getChildHtml("hozmegamenu_top"); ?>	
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link_follow_header')->toHtml();?>
			</div>
			<div class="mobile-bar-icon"><span><?php /* @escapeNotVerified */ echo __('mobile icon'); ?></span></div>
		</div>
		
		<div class="mobile-bar-content">
			<div class ="mobile-bar-close"><?php /* @escapeNotVerified */ echo __('Close'); ?></div>
			<ul class = "tabs-mobile">
				<li class="item item-menu"><?php /* @escapeNotVerified */ echo __('Menu'); ?></li>
				
				<li class="item item-setting"><?php /* @escapeNotVerified */ echo __('Setting'); ?></li>
			</ul>
			<div class="tabs-content-mobile tabs-menu">
				<?php echo $this->getChildHtml("mobilemenu"); ?>
			</div>
			<div class="tabs-content-mobile tabs-setting" style="display:none;">
				<?php echo $this->getChildHtml("top.links"); ?>
				<?php echo $this->getChildHtml("store_language_mobile"); ?>
				<?php echo $this->getChildHtml("currency_mobile"); ?>
			</div>
		</div>
</header>
<script type="text/javascript">
require(["jquery"], function($){
	$(document).ready(function(){
		<!-- show, hide mobile bar content -->
		$(".mobile-bar-icon").click(function(){
			$(".mobile-bar-content").addClass("open");
		});
		$(".mobile-bar-close").click(function(){
			$(".mobile-bar-content").removeClass("open");
		});
		
		<!-- choose tabs-->
		$(".tabs-mobile .item-menu").addClass("active");
		$(".tabs-mobile .item").click(function(){
			$(".tabs-mobile .item").removeClass("active");
			$(this).addClass("active");
		});
		$(".tabs-mobile .item-menu").click(function(){
			$(".tabs-content-mobile").css("display","none");
			$(".tabs-menu").css("display","block");
		});
		$(".tabs-mobile .item-account").click(function(){
			$(".tabs-content-mobile").css("display","none");
			$(".tabs-account").css("display","block");
		});
		$(".tabs-mobile .item-setting").click(function(){
			$(".tabs-content-mobile").css("display","none");
			$(".tabs-setting").css("display","block");
		});
		
	});

	$(window).scroll(function () {
	   if ($(this).scrollTop() > 190) {
		 $('.nav-ozmegamenu').addClass("fix-nav-ozmegamenu");
	   } else {
		$('.nav-ozmegamenu').removeClass("fix-nav-ozmegamenu");
	   }
	});	
	
	$('.page-wrapper .header-top .close').click(function(){
		$('.page-wrapper .header-top').hide();
	})
});
</script>



