<div class="main-container">
	<div class="container-inner">
		<div class="corporate-about">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('corporate_about_2')->toHtml(); ?>
		</div>
	</div>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<div class="ma-corporate-about">
		<div class="container-inner">
			<div class="corporate-about">
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('corporate_about')->toHtml(); ?>
			</div>
		</div>
	</div>
	<div class="container-inner">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_fashion_banner_images1')->toHtml(); ?>
		<?php echo $block->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('Plazathemes_Featureproductslider::featureproductslider.phtml')->toHtml();?>
	</div>
	<div class="banner-text">
		<div class="container-inner">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_fashion_banner_text')->toHtml(); ?>
		</div>
	</div>
	<div class="container-inner">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_fashion_content_home')->toHtml(); ?>
		<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
		<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
	</div>
</div>

