
<div class="main-container">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<div class="container-inner">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_book_banner_images3')->toHtml(); ?>
	</div>
	<div class="content-products">
		<div class="container-inner">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_book_content_home2')->toHtml(); ?>
		</div>	
	</div>
	<div class="time-products">
		<div class="container-inner">
			<div class="row">
				<div class="col-md-6 text-center">
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_book_banner_images_time')->toHtml(); ?>
				</div>
				<div class="col-md-6">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
				</div>
			
			</div>
		</div>	
	</div>
	<div class="proup-products">
		<div class="container-inner">		
			<div class="row">
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('Plazathemes_Newproductslider::newproductslider.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('Plazathemes_Bestsellerproduct::bestsellerproduct.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Mostviewed\Block\Products')->setTemplate('Plazathemes_Mostviewed::productslider.phtml')->toHtml();?>
				</div>
				
			</div>
		</div>
	</div>
	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
	</div>
</div>


