<div class="footer-container">	
	<div class="footer-top">
		<div class="container-inner">
			<div class="container-size">
				<div class="corporate-about">
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('corporate_about')->toHtml(); ?>
				</div>	
				<?php //echo $this->getChildHtml('footer_static')?>
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_static2')->toHtml();?>
			</div>	
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container-inner">
			<div class="container-size">
				<div class="row">
					<div class="col-md-6">
						<?php echo $this->getChildHtml('copyright')?>
						
						<?php echo $this->getChildHtml("store_switcher"); ?>
						
					</div>
					<div class="col-md-6">
						<div class="link-paypal">
							<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link_paypal')->toHtml();?>
						</div>
					</div>
				</div>
				<div id="back_top">
					<a href="#back-top"></a>
				</div>
			</div>
		</div>
	</div>
	</div>
<script type="text/javascript">
			
	require(["jquery"], function($){

	   $(window).scroll(function() {
			if($(this).scrollTop() > 300) {
				$('#back_top').fadeIn();   
			} else {
				$('#back_top').fadeOut();
			}
		});
		   $('#back_top').click(function() {
			$('body,html').animate({scrollTop:0},500);
		}); 
	   
	});	
</script>
