<div class="footer-container">
	<div class="ma-newsletter">
		<div class="container-inner">
			<div class="des-content">
				<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml();?>
			</div>
		</div>
	</div>
	<div class="footer-top">
		<div class="container-inner">
			<div class="container-size">	
				<?php //echo $this->getChildHtml('footer_static')?>
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_static')->toHtml();?>
				<div class="link-footer">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link_footer')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container-inner">
			<div class="container-size">
				<?php echo $this->getChildHtml('copyright')?>
				
				<?php echo $this->getChildHtml("store_switcher"); ?>
				<div id="back_top">
					<a href="#back-top"></a>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
			
	require(["jquery"], function($){

	   $(window).scroll(function() {
			if($(this).scrollTop() > 300) {
				$('#back_top').fadeIn();   
			} else {
				$('#back_top').fadeOut();
			}
		});
		   $('#back_top').click(function() {
			$('body,html').animate({scrollTop:0},500);
		}); 
	   
	});
	
	require(["jquery"], function($){
	$('.page-wrapper .ma-newsletter .close').click(function(){
		$('.page-wrapper .ma-newsletter').hide();
	})
	});
	
</script>
