
<div class="main-container">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<div class="container-inner">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_watch_banner_images3')->toHtml(); ?>
		<?php echo $block->getLayout()->createBlock('Plazathemes\Producttab\Block\Producttab')->setTemplate('Plazathemes_Producttab::producttab.phtml')->toHtml();?>
	</div>
	<div class="time-products">
		<div class="container-inner">
			<div class="row">
				<div class="col-md-6">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
				</div>
				<div class="col-md-6 text-center">
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_watch_banner_images_time')->toHtml(); ?>
				</div>
			</div>
		</div>	
	</div>
	<div class="proup-products">
		<div class="container-inner">		
			<div class="row">
				<div class="col-sm-6">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Recentproductslider\Block\Products')->setTemplate('Plazathemes_Recentproductslider::productslider.phtml')->toHtml();?>	
				</div>
				<div class="col-sm-6">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
	<div class="ma-newsletter">
		<div class="container-inner">
			<div class="des-content">
				<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml();?>
			</div>
		</div>
	</div>
</div>


